### ISSUE TITLE
correct "requirements" without "s"

### ISSUE THREAD

**Issue by Copinmalin** [Asi0Flammeus/LLM-Translator#1]
4. Install Required Libraries: 

- pip install -r requirements.txt

but : https://github.com/Asi0Flammeus/LLM-Translator/blob/main/requirement.txt

**Comment by Asi0Flammeus** [comment]
Resolved with [commit aeae04f](https://github.com/Asi0Flammeus/LLM-Translator/commit/aeae04f22e6a2cb1600015786bf4c7d54ae9ffb1). Requirements file has been renamed and cleaned up with only necessary libraries.
