### ISSUE TITLE
choose the translation language

### ISSUE THREAD

**Issue by Copinmalin** [Asi0Flammeus/LLM-Translator#2]
Have a language selector to limit costs or simply to have only the target language in the output folder

**Comment by Asi0Flammeus** [comment]
This feature is now implemented: for each folder, a selection of languages for the translation is asked. 

Resolved with [commit ebab3c5](https://github.com/Asi0Flammeus/LLM-Translator/commit/ebab3c5aa9ac5a8eeee2844affd6c4f3f53bb6c5).
